Class diashenrique.messageviewer.Message.SimpleMessage Extends Ens.Request [ Inheritance = left, ProcedureBlock ]
{

Property ClassMessage As %String;

Storage Default
{
<Data name="SimpleMessageDefaultData">
<Subscript>"SimpleMessage"</Subscript>
<Value name="1">
<Value>ClassMessage</Value>
</Value>
</Data>
<DefaultData>SimpleMessageDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
