 do $SYSTEM.OBJ.Load("/opt/irisapp/Installer.cls", "ck")
 set sc = ##class(App.Installer).setup() 
 set sc = ##class(App.Installer).SetAppProperties("/csp/msgviewer","/opt/irisapp/csp/")
 set sc = ##class(App.Installer).CompileCSP("/csp/msgviewer","MSGVIEWER")

 zn "MSGVIEWER"
 do $System.OBJ.LoadDir("/opt/irisapp/src","ck",,1)
 
 zn "%SYS"
 Do ##class(Security.Users).UnExpireUserPasswords("*")

halt
